### ISSUE TITLE
Remove wasm

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/fee-abstraction#48]
Had a chat with @vuong177 and @GNaD13 who felt we should remove wasm from this repository.  

I began work on a PR to do so, #47 
```[tasklist]
### Tasks
- [ ] https://github.com/osmosis-labs/fee-abstraction/pull/47
- [ ] remove wasm for sdk 46
- [ ] https://github.com/osmosis-labs/fee-abstraction/pull/37
```

**Comment by faddat** [comment]
We'll need to remove it from 45 and 46 to close this issue
